### ISSUE TITLE
Example app: create a list/menu of inputs and outputs

### ISSUE THREAD

**Issue by elmcapp** [orchetect/MIDIKit#100]
Would be nice to have a feature for macOS when a func is run it can create menu inputs and outputs with menu items of all inputs and outputs

**Comment by orchetect** [comment]
UI abstraction doesn't belong in the library, however if you're using SwiftUI then the following conform to `Identifiable` and can be used to populate lists or menus:

- `MIDI.IO.Manager`
  - `.devices.devices`
  - `.endpoints.inputs`
  - `.endpoints.outputs`

**Comment by orchetect** [comment]
An example project could be built that creates a menu, however. I'll add it to the to-do list.

**Comment by orchetect** [comment]
FYI - the best way to reference/identify endpoints is by their unique ID, since it's possible for endpoints can have identical names.

So when building menus, it's good to tag each menu item with the corresponding endpoint's unique ID.

Or if storing a reference to an endpoint for later use (ie: in UserDefaults because you want to re-connect to that endpoint the next time the app is launched, for example), store the unique ID and use that when connecting to it.

**Comment by orchetect** [comment]
I am building foundational examples and have a few built so far. I have a bit of time now and I will cover the menu building examples in the next day or so.

**Comment by orchetect** [comment]
@elmcapp @mikeHarris85 

It took quite a while but I got a thorough and complete macOS AppKit example of MIDI input and output menus. The menu selections and connections are stored to UserDefaults and restored on app relaunch as well. And if a selected endpoint no longer exists in the system, it will still remain selected in the menu but will gain a caution symbol showing that it's missing. If the endpoint reappears in the system, it will automatically reconnect and resume data flow.

https://github.com/orchetect/MIDIKit/tree/main/Examples/macOS%20AppKit/EndpointMenus

I will work on additional examples as time allows. I'd like to do a variation that uses Combo box controls in a view instead of top-level menus. And I would like to do a SwiftUI version (which will be much easier - AppKit requires a lengthy amount of code to get this all to work).

**Comment by elmcapp** [comment]
Sounds and looks great. If I may suggest it could be useful to add the features 1-5 in a readMe file inside the Xcode project. This way when someone looks at the examples they will know what all the example will do

**Comment by orchetect** [comment]
> ... add [...] a readMe file inside the Xcode project

Yes, good point. I was going to add summary README files for the projects but haven't gotten there yet. Some of the examples are simple enough that a few text labels in the example's GUI can communicate what is going on. But for more complex examples I will definitely add a README to explain the logic flow and principles. I can add this one now.

**Comment by orchetect** [comment]
Also added SwiftUI examples demonstrating this.

**Comment by orchetect** [comment]
macOS AppKit/SwiftUI and iOS SwiftUI menu examples are done. Just need to add one for iOS UIKit.

(The macOS SwiftUI example needs refactoring so that it is more in line with the iOS SwiftUI one which is on my to-do list to do soon).
 
READMEs have been added for all examples in the repo as well.
