### ISSUE TITLE
MIDI Thru Connections are not supported on this platform due to Core MIDI bugs.

### ISSUE THREAD

**Issue by NaanProphet** [orchetect/MIDIKit#164]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Hello, I am trying to send a MIDI message via USB to a MIDI controller.

When I try to setup a thru connection using the `midiManager.addThruConnection` method, it throws the following error at runtime:

`Fatal error: Error raised at top level: MIDI Thru Connections are not supported on this platform due to Core MIDI bugs.`

I saw that this issue was deferred in https://github.com/orchetect/MIDIKit/issues/19 but I wasn't sure which versions of MacOS are compatible/incompatible at runtime vs. build time. Any help would be appreciated.

**Comment by orchetect** [comment]
The issue started in macOS Big Sur (this is explained in the docs for `midiManager.addThruConnection`. It remains unresolved even in Ventura.

There is a workaround that involves using Objective-C but it hasn't been included in order to maintain MIDIKit as a pure Swift library, which allows it to run in Swift Playgrounds on iPad for instance.

Essentially, the Swift bridging of Core MIDI API seems to have an issue where passing `nil` into the first parameter of [MIDIThruConnectionCreate](https://developer.apple.com/documentation/coremidi/1508523-midithruconnectioncreate) is not interpreted as a C NULL and the connection gets created persistently no matter what. This causes all sorts of issues with orphan connections so it was safest to exempt thru connections from being made through MIDIKit until a solution can be found.

I've had a radar open with Apple for a long time with no response. And a [StackOverflow post](https://stackoverflow.com/questions/38385124/midithruconnectioncreate-always-creates-persistent-midi-thru-connection) asking for suggestions which hasn't surfaced anything new.

**Comment by orchetect** [comment]
I just spent a bit of time re-investigating this.

It appears the issue may be fixed in macOS Ventura. So I may conditionally allow thru connections but throw a normal error instead of a fatal error on unsupported systems (Big Sur and Monterey).

I've spent hours on many occasions trying to find a Swift-only workaround for the affected platforms. I'm not sure there is a way around that.

**Comment by NaanProphet** [comment]
Thanks for shedding light on this! My bad, I missed that note in the `midiManager.addThruConnection` docs.

Sounds like Big Sur and Monterey would continue to be unsupported then, and Apple just moved on and fixed it in Ventura. It's a tradeoff making MIDIKit Swift-only, but it is definitely nice for the reasons you mentioned.

Hope to see the Ventura support in an upcoming release! Thanks for your reply.

**Comment by orchetect** [comment]
I've just pushed an update to main branch that re-enables thru connections.

Now on supported systems they will work, otherwise it throws an error (try/catch) and no longer fatal errors.

I wouldn't mind also exploring a hunch I have. I am wondering if an Obj-C target (just for internal use) was added to the package and imported by way of `#if canImport(ObjCTarget)` the package could remain compatible with Swift Playgrounds while also conditionally giving me access to the Obj-C workaround that would add Big Sur / Monterey support to non-persistent thru connections.

**Comment by orchetect** [comment]
> I wouldn't mind also exploring a hunch I have

Just tested my theory. Looks like no dice.

![no-dice](https://user-images.githubusercontent.com/11605557/217725925-dbaa4e0b-0be3-4796-a766-7ec553847ada.png)

**Comment by orchetect** [comment]
I've tested it and it will work.

Basically, it's two extra lines of code that the consumer of library needs to add.

```swift
import MIDIKitC
```

and every time `midiManager.addThruConnection` is called, add this parameter:

```swift
using: MIDIKitC.CMIDIThruConnectionCreateNonPersistent
```

**Comment by orchetect** [comment]
Unfortunately I've run across another issue in testing. It's possible that thru connections are simply broken entirely on Big Sur and Monterey no matter what.

I dug out some old test projects and I recall now that even in a new, pure Obj-C project without MIDIKit at all, I was unable to get thru connections to transmit data.

There was a thread (perhaps one of many) that talked about this: https://stackoverflow.com/questions/54871326/how-is-a-coremidi-thru-connection-made-in-swift-4-2

**Comment by orchetect** [comment]
Just to recap:
- macOS 10.15 Catalina: Both Swift and Obj-C work correctly
- macOS 11 Big Sur: Thru connections are completely broken no matter what
- macOS 12 Monterey: Thru connections are completely broken no matter what
- macOS 13 Ventura: Both Swift and Obj-C work correctly

Given all of this information, there's a couple conclusions.

1. One possible workaround is to not use thru connections at all. Instead use `addInputConnection` and feed its events to an `addOutputConnection`. It achieves the same goal, albeit less performant and less convenient.
2. Given some work, MIDIKit could transparently implement that workaround on platforms that have the Code MIDI bug.

**Comment by NaanProphet** [comment]
> Unfortunately I've run across another issue in testing. It's possible that thru connections are simply broken entirely on Big Sur and Monterey no matter what.

I'm learning so much about this, thank you!

> Given all of this information, there's a couple conclusions.
> 2. Given some work, MIDIKit could transparently implement that workaround on platforms that have the Code MIDI bug.

This is a really nice idea. Transparently providing thru connections on Big Sur and Monterey would be a nice value-add for MIDIKit compared to other libraries, and still keeps them available and performant for other OS versions.

> Basically, it involves 3 extra steps.

A third option might be to provide a manual client-side workaround for Big Sur and Monterey to enable the transparent feature by doing something similar to the Objective-C workaround.

**Comment by orchetect** [comment]
> Transparently providing thru connections on Big Sur and Monterey would be a nice value-add for MIDIKit compared to other libraries

I'll work on implementing this. It shouldn't be too difficult and would remove a lot of confusion for end users.

> A third option might be to provide a manual client-side workaround for Big Sur and Monterey to enable the transparent feature by doing something similar to the Objective-C workaround.

A piece of 3rd-party software like a loopback connection router? There are options out there, yes. But I think we can do it with the above solution instead.

**Comment by orchetect** [comment]
I've complete work on an implementation that allows non-persistent thrus to always work on macOS as outlined above.

Persistent thrus are still irredeemably broken on Big Sur and Monterey and nothing can be done about that - they will throw an error.

I am also now testing iOS versions to see if they were affected during the same period in history.

- iOS 13.7: No bug
- iOS 14.5: Has bug
- iOS 15.5: Has bug
- iOS 16.2: No bug

As expected, iOS releases during the same time period are affected. I'll update MIDIKit internals and docs to reflect that it's macOS 11/12 and iOS 14/15.

**Comment by orchetect** [comment]
@NaanProphet Would you like to test main branch?

**Comment by NaanProphet** [comment]
> I've completed work on an implementation that allows **non-persistent** thrus to always work on macOS as outlined above.

Very cool!

> @NaanProphet Would you like to test main branch? Make sure you pull latest of course.

Pulled the latest, and thru connections are working for me as expected on Ventura.

```
Note On: F3 midi2(28160) 1
Note Off: F3 midi2(32768) 1
Note On: G2 midi2(27648) 1
Note Off: G2 midi2(32768) 1
Note On: C4 midi2(28160) 1
Note Off: C4 midi2(32768) 1
Note On: B2 midi2(18432) 1
Note Off: B2 midi2(32768) 1
Note On: A3 midi2(16384) 1
Note Off: A3 midi2(32768) 1
```

**Comment by orchetect** [comment]
@NaanProphet Thanks. If you have Macs with any other versions of macOS and have the opportunity to test on them that's great but no problem if not. I'm satisfied that the unit tests prove that it works as expected on different OS versions.

I will look to release a new version with the updates soon, but in the meantime you can keep using main branch.

**Comment by orchetect** [comment]
I've pushed release 0.8.2 which includes these fixes.

**Comment by NaanProphet** [comment]
> I've pushed release 0.8.2 which includes these fixes.
> 
> It's safe to assume Apple will never go back and patch the effected platforms, so MIDIKit adapts itself as best it can on those OS versions. Nothing further can be done.

Thanks very much! This is wonderful.
